import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import ThemeToggle from "./components/ThemeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`font1 font2 antialiased`}
      >
        <div className="absolute top-0 left-0 sticky h-2 w-screen bg-white z-10"></div>
        <Navbar />
        <ThemeToggle />
        {children}
      </body>
    </html>
  );
}
